#!/usr/bin/env python3
"""Slice the same projects with two OrcaSlicer builds and diff the G-code.

Use it to check that a change does not alter G-code it should not touch: build the fork and a stock
OrcaSlicer from the commit the fork is based on, then run

    python scripts/compare_gcode.py --stock "C:/stock/orca-slicer.exe" --fork "C:/fork/orca-slicer.exe" cube.3mf u1_multicolor.3mf

Each project is sliced from the command line (all plates, with the settings saved in the project). Lines
that always differ between builds (version and generation time) are ignored. The script prints, per
G-code file, whether the output is identical, and writes the full diffs to the output directory.
Exit status is 0 when every file matches and 1 otherwise.
"""

import argparse
import difflib
import pathlib
import re
import subprocess
import sys

# Lines that differ between two builds of the same code.
VOLATILE = re.compile(r"^;\s*(generated by|generated on|HEADER_BLOCK|thumbnail|version|.*OrcaSlicer\s+\d)", re.IGNORECASE)


def slice_project(exe, project, out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = [exe, "--slice", "0", "--outputdir", str(out_dir), str(project)]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  slicing failed ({exe}): exit {result.returncode}")
        print("  " + (result.stderr or result.stdout).strip().replace("\n", "\n  ")[-2000:])
    return sorted(out_dir.rglob("*.gcode"))


def normalized_lines(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        return [line.rstrip("\n") for line in f if not VOLATILE.match(line)]


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--stock", required=True, help="stock orca-slicer executable")
    parser.add_argument("--fork", required=True, help="fork orca-slicer executable")
    parser.add_argument("--out", default="gcode_compare", help="output directory (default: gcode_compare)")
    parser.add_argument("projects", nargs="+", help="3MF projects to slice")
    args = parser.parse_args()

    out = pathlib.Path(args.out)
    all_match = True
    for project in map(pathlib.Path, args.projects):
        print(f"{project.name}:")
        stock_files = slice_project(args.stock, project, out / project.stem / "stock")
        fork_files = slice_project(args.fork, project, out / project.stem / "fork")
        stock_by_name = {p.name: p for p in stock_files}
        fork_by_name = {p.name: p for p in fork_files}
        if not stock_by_name or set(stock_by_name) != set(fork_by_name):
            print(f"  different or missing outputs: stock {sorted(stock_by_name)}, fork {sorted(fork_by_name)}")
            all_match = False
            continue
        for name in sorted(stock_by_name):
            a = normalized_lines(stock_by_name[name])
            b = normalized_lines(fork_by_name[name])
            if a == b:
                print(f"  {name}: identical ({len(a)} lines)")
                continue
            all_match = False
            diff = list(difflib.unified_diff(a, b, "stock/" + name, "fork/" + name, lineterm="", n=2))
            changed = sum(1 for line in diff if line[:1] in "+-" and not line.startswith(("+++", "---")))
            diff_path = out / project.stem / (name + ".diff")
            diff_path.write_text("\n".join(diff) + "\n", encoding="utf-8")
            print(f"  {name}: {changed} lines differ, full diff in {diff_path}")
            for line in diff[:30]:
                print("    " + line)
    print("All G-code matches." if all_match else "Some G-code differs.")
    return 0 if all_match else 1


if __name__ == "__main__":
    sys.exit(main())
